# See https://aka.ms/yaml
# This pipeline to be run on PRs

trigger: none
pr:
  - master
  - v*.*.x

resources:
  containers:
    - container: centos7
      image: ucfconsort.azurecr.io/ucx/centos7:1
      endpoint: ucfconsort_registry
    - container: fedora
      image: ucfconsort.azurecr.io/ucx/fedora:3
      endpoint: ucfconsort_registry

stages:
  - stage: Logging
    jobs:
      - job: test_log
        displayName: test log
        steps:
          - bash: |
              #!/bin/bash
              echo "##vso[task.logissue type=warning]Found something that could be a problem"
           - bash: |
              #!/bin/bash
              echo "##vso[task.logissue type=error]Found something that could be a problem"



  - stage: Codestyle
    jobs:
      # Check that commit title matches code style guidelines
      - job: commit_title
        displayName: commit title
        steps:
          - checkout: self
            clean: true

          - bash: |
              set -eE
              range="remotes/origin/$(System.PullRequest.TargetBranch)..$(Build.SourceVersion)"
              ok=1
              for sha1 in `git log $range --format="%h"`
              do
                  title=`git log -1 --format="%s" $sha1`
                  if echo $title | grep -qP '^Merge |^[0-9A-Z/_\-]*: \w'
                  then
                      echo "Good commit title: '$title'"
                  else
                      echo "Bad commit title: '$title'"
                      ok=0
                  fi
              done
              if [ $ok -ne 1 ]
              then
                 url="https://github.com/openucx/ucx/wiki/Guidance-for-contributors#general-guidelines"
                 echo "##vso[task.logissue type=error]Bad commit title(s), see $url for more info."
                 echo "##vso[task.complete result=Failed;]"
              fi
            condition: eq(variables['Build.Reason'], 'PullRequest')

