# See https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: myTest
    source: 'UCX snapshot'
    trigger: true

steps:
  - script: echo Hello world
    displayName: 'Run one-line script'

extends:
  template: main-pipeline.yml

