# See https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: myTest
    source: 'UCX test'
    trigger: true


steps:
  - script: echo Triggered by UCX PR
    displayName: 'Run one-line script'
