# See https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: rebaseMainUcx
    source: 'UCX PR'
    project: ucx
    trigger: true


steps:
  - script: echo Triggered by UCX PR
    displayName: 'Run one-line script'
