# See https://aka.ms/yaml
# This pipeline to be run on PRs

trigger: none

resources:
  pipelines:
  - pipeline: rebaseMainUcx
    source: 'UCX test'
    project: UCX
    trigger: true


steps:
  - script: echo Triggered by UCX test
    displayName: 'Run one-line script'
