# See https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: myTest
    source: 'UCX snapshot'
    trigger: true

extends:
  template: templates/resources.yml

stages:
  - template: templates/main-stages.yml

